# Generated by Django 5.0.6 on 2024-11-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_rename_auhor_author_rename_books_library_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='book',
            new_name='books',
        ),
    ]
