# Generated by Django 5.0.6 on 2024-11-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_rename_book_library_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=1980),
            preserve_default=False,
        ),
    ]
